/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutProjectRouteImport } from './routes/about-project'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as WhoGuidelinesRouteImport } from './routes/who-guidelines'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutProjectRoute = AboutProjectRouteImport.update({
  id: '/about-project',
  path: '/about-project',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoGuidelinesRoute = WhoGuidelinesRouteImport.update({
  id: '/who-guidelines',
  path: '/who-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-project': typeof AboutProjectRoute
  '/prediction': typeof PredictionRoute
  '/who-guidelines': typeof WhoGuidelinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-project': typeof AboutProjectRoute
  '/prediction': typeof PredictionRoute
  '/who-guidelines': typeof WhoGuidelinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-project': typeof AboutProjectRoute
  '/prediction': typeof PredictionRoute
  '/who-guidelines': typeof WhoGuidelinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about-project' | '/prediction' | '/who-guidelines'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-project' | '/prediction' | '/who-guidelines'
  id: '__root__' | '/' | '/about-project' | '/prediction' | '/who-guidelines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutProjectRoute: typeof AboutProjectRoute
  PredictionRoute: typeof PredictionRoute
  WhoGuidelinesRoute: typeof WhoGuidelinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-project': {
      id: '/about-project'
      path: '/about-project'
      fullPath: '/about-project'
      preLoaderRoute: typeof AboutProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-guidelines': {
      id: '/who-guidelines'
      path: '/who-guidelines'
      fullPath: '/who-guidelines'
      preLoaderRoute: typeof WhoGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutProjectRoute: AboutProjectRoute,
  PredictionRoute: PredictionRoute,
  WhoGuidelinesRoute: WhoGuidelinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
